default_platform(:ios)

platform :ios do
  desc "🚀 Compilar y subir a TestFlight"

  lane :beta do
    # 👷‍♂️ Compilar la app
    build_app(
      scheme: "Zenti", # Asegúrate que este scheme exista y esté compartido
      export_method: "app-store",
      export_options: {
        signingStyle: "automatic",
        compileBitcode: true,
        uploadSymbols: true,
        teamID: "XK4QBKULJR"
      },
      output_directory: "./build", # Opcional, dónde guardar el .ipa
      output_name: "Zenti.ipa"
    )

    # ☁️ Subir a TestFlight
    upload_to_testflight(
      username: ENV["APPLE_ID"],
      skip_waiting_for_build_processing: true,
      app_identifier: "com.teranov.zentiapp"
    )
  end
end
